username=input("what is your name?")
food=input("what is your favourite foord?")
music=input("what is your favourite music?")
live=input("where do you live?")

print("you are")
print(username)
print("you are probably hungry for",food)
print("and you are definitely getting your groove on to",music)
print("lieving in the amazing",live)
